name: Deploy OC-06 to GitHub Pages

on:
  push:
    branches:
      - release  # Changez si votre branche principale est différente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 'latest'

    - name: Install dependencies
      run: bun install

    - name: Build project
      run: bun run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Assurez-vous que c'est le répertoire de sortie de Vite.js
