name: 06 Fisheye Deploy to GitHubPages

on:
  push:
    branches:
      - release  # Branch de production 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 'latest'  # Assurez-vous d'utiliser la dernière version stable de Bun

    - name: Install dependencies
      run: bun install

    - name: Build project
      run: bun run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: /dist  # Vérifiez que c'est le répertoire de sortie de votre projet Vite.js
